engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.jsx"
  - "**.module"
exclude_paths: []
env:
  browser: true
  es6: true
  node: true
